version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /javaapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /javaapp/docker-credentials/password

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Installing Maven..."
      
  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean install
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_USERNAME/springboot-codebuild-javaapp:july02-07" .
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin docker.io
      - docker push "$DOCKER_REGISTRY_USERNAME/springboot-codebuild-javaapp:july02-07"
      - docker logout
  post_build:
    commands:
      - echo "Build completed successfully!"

  artifacts:
    files:
      - target/*.jar
