version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Installing Maven..."
      
  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean install
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - target/*.jar
