# Stage1-Build JAR(Java Application Runtime) by Maven
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app
COPY . .
# Below step use to create JAR 
RUN mvn clean install

# Stage2-Copy JAR file from Stage1 & Execute
FROM openjdk:17-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar /app/hello-world.jar
EXPOSE 8080
CMD ["java", "-jar", "hello-world.jar"]
